services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://houze-work:vUG5kR3J7DlPDY79@cluster0.3n1nngb.mongodb.net/houze-lucky-wheel?appName=dev
      - PORT=3000
    restart: unless-stopped
